# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  unit:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 11
        uses: actions/setup-node@v1
        with:
          node-version: 11
      - run: npm ci
      - run: npm run test:unit
  e2e:
    runs-on: ubuntu-16.04
    name: End to End Tests
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 11
      - name: Install dependencies
        run: npm ci
      - run: node -v
      - name: Setup Firebase CLI
        uses: w9jds/firebase-action@master
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          start: npm run serve
          wait-on: http://localhost:8081/
          browser: chrome
